USE Vente_db
GO

INSERT INTO CLIENT VALUES ('CL01','ALAMI','Tanger')
INSERT INTO CLIENT VALUES('CL02','FIKRI','CASA')
INSERT INTO CLIENT VALUES('CL03','NAJI','Rabat')
INSERT INTO CLIENT VALUES('CL04','NASIRI','CASA')
INSERT INTO CLIENT VALUES('CL05','KADIRI','CASA')
GO